spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": info.mouts.orderservice.dto
        "[spring.json.value.default.type]": info.mouts.orderservice.dto.OrderRequestDTO
        "[spring.json.use.type.headers]": false
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: ${spring.kafka.consumer.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.trusted.packages]": info.mouts.orderservice.dto
        "[spring.json.use.type.headers]": false

  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: mouts_user
    password: mouts_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            "[non_contextual_creation]": true
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 10m
      use-key-prefix: true
      cache-null-values: false

springdoc:
  override-with-generic-response: false

app:
  kafka:
    orders-received-topic: orders.received.v1
    dlt-orders-topic: orders.dlt.v1
    orders-processed-topic: orders.processed.v1
