global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "moutsti-orderservice-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["orders-service-app:8080"]
      - labels:
          application: "moutsti-orderservice"
